#!/usr/bin/env python3
"""Generate web/src/schema.generated.js from shared/*.json (run after editing the schema).
`--check` exits non-zero if the generated file is out of date (used in CI)."""
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
schema = json.loads((ROOT / "shared/voice_profile.schema.json").read_text())
ref = json.loads((ROOT / "shared/reference_profile.json").read_text())
out = ("/* GENERATED by scripts/gen_schema.py from shared/*.json. Do not edit by hand. */\n"
       f"window.VOICE_SCHEMA_DOC = {json.dumps(schema, indent=2)};\n"
       f"window.VOICE_REFERENCE = {json.dumps(ref, indent=2)};\n")
target = ROOT / "web/src/schema.generated.js"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != out:
        print("web/src/schema.generated.js is out of date: run python scripts/gen_schema.py"); sys.exit(1)
    print("schema.generated.js is up to date")
else:
    target.write_text(out); print("wrote", target.relative_to(ROOT))
